'use strict'
const { execSync } = require('child_process')
const { resolveConflictsInFiles } = require('./conflict-resolver.cjs')

function run(cmd, cwd) {
  return execSync(cmd, { cwd, encoding: 'utf8', stdio: 'pipe' }).trim()
}

// Returns { exists, hadConflicts, action, branch }
async function manageBranch(connectorId, cwd = process.cwd(), options = {}) {
  const branch = `connector/${connectorId}`
  const currentBranch = getCurrentBranch(cwd)

  const remoteBranches = (() => {
    try { return run('git branch -r', cwd) } catch { return '' }
  })()

  const localBranches = (() => {
    try { return run('git branch', cwd) } catch { return '' }
  })()

  const existsRemote = remoteBranches.includes(`origin/${branch}`)
  const existsLocal  = localBranches.split('\n').some(b => b.trim().replace(/^\*\s*/, '') === branch)

  if (options.dryRun || !options.applyGit) {
    return {
      exists: existsRemote || existsLocal,
      hadConflicts: false,
      action: existsRemote || existsLocal ? 'would-pull' : 'would-create',
      branch,
      currentBranch,
      dryRun: true,
    }
  }

  if (existsRemote || existsLocal) {
    // Pull existing branch
    if (!existsLocal) {
      run(`git fetch origin ${branch}`, cwd)
      run(`git checkout -b ${branch} origin/${branch}`, cwd)
    } else {
      run(`git checkout ${branch}`, cwd)
      try { run(`git pull origin ${branch}`, cwd) } catch { /* no remote yet */ }
    }
    const conflictedFiles = getConflictedFiles(cwd)
    let conflictResolutions = []
    if (conflictedFiles.length > 0) {
      conflictResolutions = await resolveConflictsInFiles(conflictedFiles)
      if (conflictResolutions.some(r => r.resolved)) {
        run('git add -u', cwd)
      }
    }
    return { exists: true, hadConflicts: conflictedFiles.length > 0, action: 'pulled', branch, currentBranch, conflictResolutions }
  }

  // Create from the repo's default branch; if checkout fails (dirty tree) branch from current HEAD
  const defaultBranch = getDefaultBranch(cwd)
  try {
    run(`git checkout ${defaultBranch}`, cwd)
    try { run(`git pull origin ${defaultBranch}`, cwd) } catch { /* offline / no remote ok */ }
  } catch {
    // Dirty working tree or default branch unreachable — branch from current HEAD
  }
  run(`git checkout -b ${branch}`, cwd)
  return { exists: false, hadConflicts: hasConflicts(cwd), action: 'created', branch, currentBranch }
}

// Commits generated files and (optionally) pushes
async function commitFiles(branch, connectorName, cwd = process.cwd(), options = {}) {
  if (options.dryRun || !options.applyGit) return { committed: false, branch, dryRun: true }
  run('git add src/connectors/', cwd)
  try { run(`git add src/index.ts`, cwd) } catch { /* ok */ }
  try { run(`git add playground/connectors.registry.cjs`, cwd) } catch { /* ok */ }

  const msg = `feat(connector): generate ${connectorName} connector\n\nAuto-generated by complyment-connectors-sdk generator`
  try {
    run(`git commit -m "${msg.replace(/"/g, '\\"')}"`, cwd)
  } catch (err) {
    if (/nothing to commit/i.test(err.message || '')) return { committed: false, branch, reason: 'nothing-to-commit' }
    throw err
  }
  return { committed: true, branch }
}

async function pushBranch(branch, cwd = process.cwd(), options = {}) {
  if (options.dryRun || !options.applyGit) return { pushed: false, branch, dryRun: true }
  run(`git push -u origin ${branch}`, cwd)
  return { pushed: true, branch }
}

function hasConflicts(cwd) {
  return getConflictedFiles(cwd).length > 0
}

function getConflictedFiles(cwd) {
  try {
    const output = run('git diff --name-only --diff-filter=U', cwd)
    return output ? output.split('\n').filter(Boolean).map(f => require('path').join(cwd, f)) : []
  } catch { return [] }
}

function getCurrentBranch(cwd) {
  try { return run('git branch --show-current', cwd) } catch { return null }
}

function getDefaultBranch(cwd) {
  try {
    const remote = run('git remote show origin', cwd)
    const match = remote.match(/HEAD branch:\s*(.+)/)
    if (match) return match[1].trim()
  } catch { /* no remote */ }
  try { run('git rev-parse --verify main', cwd); return 'main' } catch {}
  try { run('git rev-parse --verify master', cwd); return 'master' } catch {}
  return 'main'
}

module.exports = { manageBranch, commitFiles, pushBranch, hasConflicts, getConflictedFiles }
