'use strict'
const { execSync } = require('child_process')

function run(cmd, cwd) {
  return execSync(cmd, { cwd, encoding: 'utf8', stdio: 'pipe' }).trim()
}

// Creates a GitHub PR using `gh` CLI. Returns PR URL.
async function createPR(opts) {
  const { branch, connectorName, mode, analysis, reviewResult, testResult, cwd = process.cwd(), dryRun = true, createPr = false } = opts

  const prefix = mode === 'update' ? 'update' : 'feat'
  const title  = `${prefix}(connector): ${mode} ${connectorName}`

  const ops = (analysis.operationsFound || []).join(', ')
  const testLine = testResult?.passed ? `✓ Tests passed` : `⚠ Tests: ${testResult?.summary || 'unknown'}`
  const score    = reviewResult?.score ?? '—'
  const verdict  = reviewResult?.verdict ?? '—'

  const body = `## ${mode === 'update' ? 'Updated' : 'New'} Connector: ${connectorName}

**Auth:** ${analysis.authType}
**Base URL:** ${analysis.baseUrl}
**Operations:** ${ops}

## Test Results
${testLine}

## Code Review
Score: ${score}/100 | ${verdict}
${(reviewResult?.issues || []).filter(i => i.severity !== 'info').map(i => `- ⚠ ${i.file}: ${i.message}`).join('\n')}

🤖 Auto-generated by complyment-connectors-sdk generator`

  if (dryRun || !createPr) return { url: null, title, branch, draftBody: body, dryRun: true }

  if (process.env.GITHUB_TOKEN) {
    try {
      const repo = getRepo(cwd)
      const { Octokit } = require('@octokit/rest')
      const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN })
      const pr = await octokit.pulls.create({
        owner: repo.owner,
        repo: repo.repo,
        title,
        body,
        base: process.env.GITHUB_BASE_BRANCH || 'main',
        head: branch,
        draft: process.env.GITHUB_PR_DRAFT !== 'false',
      })
      return { url: pr.data.html_url, title, branch, number: pr.data.number }
    } catch (err) {
      if (process.env.GENERATOR_STRICT_GITHUB === 'true') throw err
    }
  }

  try {
    const url = run(
      `gh pr create --title "${title.replace(/"/g, '\\"')}" --body "${body.replace(/"/g, '\\"').replace(/\n/g, '\\n')}" --base main --head ${branch}`,
      cwd
    )
    return { url, title, branch }
  } catch (err) {
    // gh not installed or no GitHub remote — return draft info
    return { url: null, title, branch, draftBody: body, error: err.message }
  }
}

function getRepo(cwd) {
  const remote = run('git remote get-url origin', cwd)
  const match = remote.match(/github\.com[:/]([^/]+)\/(.+?)(?:\.git)?$/)
  if (!match) throw new Error(`Could not parse GitHub repo from origin remote: ${remote}`)
  return { owner: match[1], repo: match[2] }
}

module.exports = { createPR }
